### ISSUE TITLE
Support for subdirectories with relative linked styles and javascript

### ISSUE THREAD

**Issue by michaelrosario** [emmercm/metalsmith-html-sri#81]
For sites with subdirectories 

**Structure**
index.html
/folder/index.html
/folder2/index.html

**Same assets on each file**
`<link href="/relativeUrl/file.css" />`
`<script src="/relativeUrl/file.js"></script>`

**Issue**
Only the main index.html is receiving the SRI.

**Comment by emmercm** [comment]
Just seeing this now, I think I have my GitHub notifications configured poorly.

Are you saying that the SRI attributes are only added to links to those local resources in `index.html` and not the other HTML files?

Could you provide a quick example contents for each of those HTML files?

**Comment by michaelrosario** [comment]
I was able to get it to work using these edits:
`https://github.com/michaelrosario/metalsmith-html-sri/commit/96bc2c8ab4c1bcc9d5277adfd2ee6c6c2d0059bd#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1`

The structure is as follows:
src/index.html
src/page1/index.html
src/page2/index.html

Only `src/index.html` was getting the proper SRI.

**Comment by emmercm** [comment]
The key was that leading `/` in the resource path, great find!

Pretty sure v0.3.0 (https://github.com/emmercm/metalsmith-html-sri/pull/94) fixed it, can you try it?

**Comment by michaelrosario** [comment]
Thanks @emmercm will try!

**Comment by michaelrosario** [comment]
Confirming that this update fixed that issue.  Thank you!

**Comment by emmercm** [comment]
You're welcome, thanks so much for reporting this!
